### PR TITLE
updates for conda

### PR DESCRIPTION
**Pull request by vivekbhr**
Hi @FelixKrueger 

I have added SNPsplit (v0.3.3) to [bioconda](bioconda.github.io) and the addition went ok, but then I realized the use of `/usr/bin/perl -w ` made `tag2sort` unusable. I have added the fix for that, and another fix removing extra `--dir` command. Could you please add these changes and make a new release **(0.3.4)**  ? I edited the version names already in the files, but might need fixed. Once you do this i can add a new recipe to bioconda and we would have this working.

Thanks
Vivek

### CODE REVIEW

**Comment by FelixKrueger** [comment]
Thanks for that Vivek. I'll take a look when I am not so tired, just waiting at the airport for late night flight....

**Comment by vivekbhr** [comment]
@FelixKrueger just pinging again as a reminder. :)

**Comment by FelixKrueger** [comment]
Don't worry, the email is still in my inbox. The issue is that it is a bank holiday and I am abroad on vacations in gorgeous weather... I'll try to look soon though.

**Comment by vivekbhr** [comment]
oh wow. I thought you forgot :) No problem. Enjoy your holidays :+1:

**Comment by FelixKrueger** [comment]
Sorry for taking to so long, looks all fine. Cheers, Felix

**Pull request merged**
